[project]
name = "lifelog"
version = "0.1.0"
description = "A terminal-based health, habit, task, life tracker."
authors = [{ name = "Zach McKinnon" }]
readme = "README.md"
license = { text = "MIT" }
dependencies = [
    # Universal
    "typer",
    "rich",
    "pyfiglet",
    "termplotlib",
    "numpy",
    "requests",
    "scipy",
    "tomlkit",
    "pandas<2.0; platform_machine != 'armv7l'",  # Avoid compilation issues on ARM
    "pandas>=1.3.0,<2.0; platform_machine == 'armv7l'",  # Specific ARM version
    "toml",
    "plotille",
    "plotext",
    "pydantic",
    "flask",
    "npyscreen",
    "pyyaml", 
    "gunicorn",
    "pendulum>=2.0",

    # Windows only
    "windows-curses; sys_platform == 'win32'",
    "pywin32; sys_platform == 'win32'",
]
requires-python = ">=3.8"

[project.optional-dependencies]
# Lightweight version for ARM devices with limited resources
arm = [
    "polars",  # Lightweight pandas alternative
]
# Full analytics for powerful machines
analytics = [
    "pandas>=2.0",
    "matplotlib",
    "seaborn",
]

[project.scripts]
llog = "lifelog.llog:lifelog_app"

[build-system]
requires = ["setuptools >= 77.0.3", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["lifelog*"]

[tool.setuptools.package-data]
"lifelog" = ["config/*.toml", "*.py"] 
