[project]
name = "lifelog"
version = "0.1.0"
description = "A terminal-based health, habit, task, life tracker."
authors = [{ name = "Zach McKinnon" }]
readme = "README.md"
license = { text = "MIT" }
dependencies = [
    "typer",
    "rich",
    "termplotlib",
    "numpy",
    "requests",
    "scipy",
    "tomlkit",
    "pandas",
    "toml",
    "plotille",
    "plotext",
    "pywin32; sys_platform == 'win32'" ,
]
requires-python = ">=3.8"

[project.scripts]
llog = "lifelog.llog:lifelog_app"

[build-system]
requires = ["setuptools >= 77.0.3", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["lifelog*"]

[tool.setuptools.package-data]
"lifelog" = ["config/*.toml"]
