[project]
name = "lifelog"
version = "0.1.0"
description = "A terminal-based health, habit, task, life tracker."
authors = [{ name = "Zach McKinnon" }]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.8"
dependencies = [
    "flask==3.1.1",
    "typer==0.16.0",
    "rich==14.0.0",
    "termplotlib==0.3.9",
    "numpy==2.3.0",
    "requests==2.32.4",
    "scipy==1.15.3",
    "tomlkit==0.13.3",
    "pandas==2.3.0",
    "toml==0.10.2",
    "plotext==5.3.2",
    # Not present in requirements.txt but in your original:
    "plotille",
    "pydantic",
    # OS-specific dependencies
    "windows-curses; sys_platform == 'win32'",
    "pywin32; sys_platform == 'win32'",
    # Optional: npyscreen is in your requirements.txt. If you use it, add it:
    "npyscreen==4.10.5",
]
requires-python = ">=3.8"

[project.scripts]
llog = "lifelog.llog:lifelog_app"

[build-system]
requires = ["setuptools >= 77.0.3", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["lifelog*"]

[tool.setuptools.package-data]
"lifelog" = ["config/*.toml", "*.py"] 
