[categories]
work = "Work related tasks"
school = "School or study tasks"
home = "Home related tasks"
personal = "Personal tasks"
health = "Health and fitness tasks"

[tracker]
[mood]
[water]

[paths]
CONFIG_FILE = "~/.lifelog/config.toml"
TRACK_FILE = "~/.lifelog/lifelog_track.json"
TIME_FILE = "~/.lifelog/lifelog_time.json"
TASK_FILE = "~/.lifelog/lifelog_tasks.json"
DAILY_QUOTE_FILE = "~/.lifelog/daily_quote.json"
ENV_DATA_FILE = "~/.lifelog/environment.json"
FEEDBACK_FILE = "~/.lifelog/feedback.json"
FC_FILE = "~/.lifelog/initialized.json"

[aliases]
m = "mood"
w = "water"
sl = "sleep"

[cron.recur_auto]
schedule = "0 0 * * *"
command = "llog task auto_recur"

[cron.env_sync]
schedule = "0 */4 * * *"
command = "llog env sync-all"

[settings]
default_importance = 3
show_completed_tasks = false

[meta]
initialized = false
