
[metric.mood]
type = "int"
min = 1
max = 10
description = "Mood from 1 (bad) to 10 (great)"

[metric.sleepq]
type = "int"
min = 1
max = 10
description = "Sleep quality"

[metric.energy]
type = "int"
min = 1
max = 10
description = "Energy Level"

[paths]
log_file = "~/.lifelog.json"
time_file = "~/.lifelog_time_tracking.json"
habit_file = "~/.lifelog_habits.json"
config_file = "~/.lifelog/config.toml"

[aliases]
m = "mood"
a = "anxiety"
w = "water"

[cron.refresh_tasks]
schedule = "0 7 * * *"
command = "llog task refresh"

[cron.daily_summary]
schedule = "30 20 * * *"
command = "llog summary daily"

[cron.recur_auto]
schedule = "0 0 * * *"
command = "llog task auto_recur"

[settings]
default_importance = 3
show_completed_tasks = false

[defaults.task]
recur_format = "every:X" # for future customization
due_format = "+XdT18:00"
