# GitHub Actions workflow for creating releases
name: Create Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v0.1.0

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
        
    - name: Build packages
      run: |
        python -m build
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*.whl
          dist/*.tar.gz
        body: |
          ## 🚀 Lifelog Release ${{ github.ref_name }}
          
          ### Installation
          ```bash
          # Download and install the wheel file
          pip install lifelog-${{ github.ref_name }}-py3-none-any.whl
          llog setup
          ```
          
          ### What's New
          - Enhanced CLI interface with Claude-inspired design
          - Raspberry Pi Zero 2W optimization
          - Advanced analytics and reporting
          - Multi-device sync capabilities
          
          ### Quick Start
          ```bash
          llog setup                    # Initial configuration
          llog time start "Work"        # Start time tracking
          llog task add "Test task"     # Add tasks
          llog report summary           # View insights
          ```
          
          See [INSTALL.md](INSTALL.md) for detailed installation instructions.
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}